# Einsum

## Resources 

### Article
- In depth https://obilaniu6266h16.wordpress.com/2016/02/04/einstein-summation-in-numpy/
- For pytorch - https://rockt.github.io/2018/04/30/einsum

### Video
- https://www.youtube.com/watch?v=pkVwUVEHmfI&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz&index=31

### Notes


- **Free indices** are the indices used in the output specification. They are associated with the outer for-loops.
    
- **Summation indices** are all other indices: those that appear in the argument specifications but not in the output specification. They are so called because they are summed out when computing the output tensor. They are associated with the inner for-loops.

***Free indices*** *are those used to iterate over every output element, while **summation indices** are those used to compute and sum over the product terms required.*    1301060001724923


In [2]:
import torch
torch.__version__

'1.7.1'

In [12]:
a = torch.arange(3,9).reshape(2,3)
a

tensor([[3, 4, 5],
        [6, 7, 8]])

In [14]:
row_sum = torch.einsum("ij->j",a)
row_sum

tensor([ 9, 11, 13])

In [15]:
col_sum = torch.einsum("ij->i",a)
col_sum

tensor([12, 21])